### PR TITLE
Added steps to install DuckDB in QGIS at startup

### PR DESCRIPTION
**Pull request by mtravis**
I think this is a good way to manage the DuckDB dependency. It should install the latest version. #27 

We could probably adapt the init.py to check and make sure it's the correct version as per #34 
Though as that problem arose from using OSGeo4W installer.  

You can check this in the python console using the OSGeo4W installer and hopefully this fix will stop that? #

```
import duckdb
duckdb.sql("PRAGMA version;")
```

### CODE REVIEW

**Comment by cholmes** [comment]
Awesome! I was thinking last night we should at least try to not load duckdb immediately so the plugin wouldn't just fail. But this is an even better solution.

Yesterday I started working on some code to check the DuckDB version and give people a warning that they should upgrade. Probably not bad to have that in there just for extra safety.

**Comment by mtravis** [comment]
@cholmes I've assumed it's ok to merge 

Definitely agree that it would be good to check for a minimum version of DuckDB

**Comment by cholmes** [comment]
Cool. I'll review it on main, and try to do the minimum version check, and then cut a release. thanks!

**Comment by cholmes** [comment]
@mtravis - unfortunately this isn't working for me. I installed a fresh qgis on my mac, that has no duckdb. The code gets called, but it seems to start a new qgis (I get the intro screens going by), and then it freezes. And in the qgis that called the code I get 4 errors, one for each of pip, -m, duckdb, install:

Screenshot 2024-12-09 at 8 22 08 AM

I have to force quite the qgis that it started up.

I tried taking off the --user flag, but that didn't help at all. 

I tried asking chatgpt and it recommended the same thing that you did, and its only idea was to change the order of things called. I'll keep digging, but let me know if you have any ideas.

**Comment by cholmes** [comment]
Ok, I think I got this working, using the pip install method that Mark posted instead of using `sys.executable`. I dug into it a bunch, trying to get it to grab my exact QGIS installation location, which I eventually got (with some fairly complicated code), but then it was still not installing DuckDB.

Going back to Mark's method worked perfectly though, and it seems like a few people have verified it works. I'll put up the PR soon.

@mtravis - next time could you hold off on merging until I get a chance to review? I know I've just been committing to main, but I'm starting to do PR's, and if we get critical mass I'd be happy for others to review mine. But I think with that we can identify if it may not work and talk about options before actually merging. I also managed to catch that the time stamps got overwritten, and likely would have caught that before merging.

**Comment by cholmes** [comment]
Oh, and if you have time to test it out that'd be great, to be sure it actually works across platforms. Just use the zip download from https://github.com/cholmes/qgis_plugin_gpq_downloader/releases/tag/v0.3.0 I want to be sure it works for more people than just me before I upload to qgis.

**Pull request merged**
